name: .NET5 build and test

on:
  push:
    branches: 
        - master
        - 'feature/**'
  pull_request:
    branches: 
        - master
        - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:  5.0.100
    - name: Install dependencies
      run:  dotnet restore
    - name: Build
      run:  dotnet build --configuration Release --no-restore
